name: Deploy notes api

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run jest tests
              run: npm run test

            - name: prisma generate
              run: npx prisma generate

            - name: Build
              run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Render
              uses: renderapp/github-action@v0.4.2
              with:
                  renderToken: ${{ secrets.RENDER_TOKEN }}
                  renderFile: render.yaml
