name: Deploy to Render

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: prisma generate
              run: npm run generate

            - name: prisma generate dev
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
              run: npm run generate:dev

            - name: Run tests (Dev)
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
              run: npm run test

            - name: Build
              run: npm run build

            - name: Deploy to Render
              uses: renderapp/render-deploy-github-action@v1
              with:
                  renderToken: ${{ secrets.RENDER_TOKEN }}
                  renderFile: render.yaml
